version: '3'
services:
  geth:
    env_file:
      - .env.production
    build:
      dockerfile: Dockerfile.ether
      context: .
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - geth-data:/root
    container_name: geth
    restart: always
    networks:
      geth-private-net:
  server:
    env_file:
      - .env.production
    build:
      dockerfile: Dockerfile.server
      context: .
    ports:
      - ${PORT}:${PORT}
    container_name: server
    restart: always
    networks:
      geth-private-net:

networks:
  geth-private-net:
    driver: bridge
    ipam:
      config:
      - subnet: ${SUBNET}

volumes:
  geth-data:
