FROM ethereum/client-go:alltools-latest

USER root
WORKDIR /root

COPY genesis.json .
COPY scripts/launch.sh /root/launch.sh
COPY scripts/clef.sh /root/clef.sh
COPY ./keystore .ethereum/keystore


ENV NETWORK_ID=14

RUN geth  init ./genesis.json
# RUN  echo ok | echo password | clef init

ENTRYPOINT [ "./launch.sh" ]
# "sh","./clef.sh", "&",
