version: '3.5'
services:
  proxy:
    build: ./packages/proxy
    ports:
      - ${PROXY_PORT}:80
    networks:
      geth-private-net:
    restart: always
    container_name:  proxy
    depends_on:
      - network
      - contracts
      - compiler
  network:
    env_file:
      - .env
    build: ./packages/network
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - geth-data:/root/.ethereum
    container_name: network
    restart: always
    networks:
      geth-private-net:
  contracts:
    build: ./packages/contracts
    env_file:
      - .env
    environment:
      - PORT=5000
    volumes:
      - constracts-db:/app/database
    container_name: contracts
    restart: always
    depends_on:
      - network
      - compiler
    networks:
      geth-private-net:
  compiler:
    build: ./packages/compiler
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - PORT=5000
    volumes:
      - compiler-static:/app/static
    container_name: compiler
    restart: always
    networks:
      geth-private-net:

networks:
  geth-private-net:
    driver: bridge
    name: geth-net
    attachable: true

volumes:
  geth-data:
  compiler-static:
  constracts-db:
