version: '3'
services:
  proxy:
    image: nginx:alpine
    ports:
      - ${PORT}:80
    volumes:
      - ./configs/nginx:/etc/nginx/templates
    networks:
      geth-private-net:
    depends_on:
      - network
      - contracts
  network:
    env_file:
      - .env.production
    build: ./packages/network
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - geth-data:/root
    container_name: network
    restart: always
    networks:
      geth-private-net:
  contracts:
    build: ./packages/contracts
    env_file:
      - .env.production
    environment:
      - PORT=5000
    container_name: contracts
    restart: always
    depends_on:
      - network
    networks:
      geth-private-net:

networks:
  geth-private-net:
    driver: bridge
    ipam:
      config:
      - subnet: ${SUBNET}

volumes:
  geth-data:
