version: '3.5'
services:
  proxy:
    build: ./apps/proxy
    ports:
      - ${PROXY_PORT}:80
    networks:
      geth-private-net:
    restart: always
    container_name:  proxy
    depends_on:
      - network
      - ms.contracts
      - ms.compiler
      - ms.auth
  network:
    build: ./apps/network
    env_file:
      - .env
    volumes:
      - geth-data:/root/.ethereum
    container_name: network
    restart: always
    networks:
      geth-private-net:
  ms.auth:
    build: ./apps/auth
    env_file:
      - .env
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${AUTH_DATABASE_NAME}
    restart: always
    container_name: ms.auth
    networks:
      geth-private-net:
    depends_on:
      - database
  ms.contracts:
    build: ./apps/contracts
    env_file:
      - .env
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${CONTRACTS_DATABASE_NAME}
    volumes:
      - constracts-db:/app/database
    container_name: ms.contracts
    restart: always
    depends_on:
      - network
      - ms.compiler
    networks:
      geth-private-net:
  ms.compiler:
    build: ./apps/compiler
    env_file:
      - .env
    environment:
      - PORT=5000
    volumes:
      - compiler-static:/app/static
    container_name: ms.compiler
    restart: always
    networks:
      geth-private-net:
  database:
    image: postgres:alpine
    ports:
      - ${DATABASE_OUTER_PORT:-0}:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - main-database-data:/var/lib/postgresql/data
    networks:
      geth-private-net:
    container_name: database
    restart: always

networks:
  geth-private-net:
    driver: bridge
    name: geth-net
    attachable: true

volumes:
  geth-data:
  compiler-static:
  constracts-db:
  main-database-data:
